#ifndef MICROPHONE__H
#define MICROPHONE__H

#define ADC_UNIT ADC_UNIT_1

#if ADC1_GPIO_32
    #define MICROPHONE_GPIO ADC_CHANNEL_4
#elif ADC1_GPIO_33
    #define MICROPHONE_GPIO ADC_CHANNEL_5
#elif ADC1_GPIO_34
    #define MICROPHONE_GPIO ADC_CHANNEL_6
#elif ADC1_GPIO_35
    #define MICROPHONE_GPIO ADC_CHANNEL_7
#elif ADC1_GPIO_36
    #define MICROPHONE_GPIO ADC_CHANNEL_0
#elif ADC1_GPIO_39
    #define MICROPHONE_GPIO ADC_CHANNEL_3
#endif

#endif